extern const GeoLayout totwc_area_1_geo[];
extern const GeoLayout totwc_area_1[];
extern const Collision totwc_area_1_collision[];
extern const MacroObject totwc_area_1_Area_root_macro_objs[];
extern Vtx totwc_dl_Airplane_001_mesh_vtx_0[635];
extern Gfx totwc_dl_Airplane_001_mesh_tri_0[];
extern Vtx totwc_dl_Airplane_001_mesh_vtx_1[63];
extern Gfx totwc_dl_Airplane_001_mesh_tri_1[];
extern Vtx totwc_dl_Airplane_001_mesh_vtx_2[28];
extern Gfx totwc_dl_Airplane_001_mesh_tri_2[];
extern Vtx totwc_dl_EngineA_Cylinder_002_mesh_vtx_0[103];
extern Gfx totwc_dl_EngineA_Cylinder_002_mesh_tri_0[];
extern Vtx totwc_dl_EngineB_Cylinder_001_mesh_vtx_0[103];
extern Gfx totwc_dl_EngineB_Cylinder_001_mesh_tri_0[];
extern Vtx totwc_dl_Engine_Support_Cube_001_mesh_vtx_0[24];
extern Gfx totwc_dl_Engine_Support_Cube_001_mesh_tri_0[];
extern Vtx totwc_dl_TailFin_Cube_001_mesh_vtx_0[122];
extern Gfx totwc_dl_TailFin_Cube_001_mesh_tri_0[];
extern Vtx totwc_dl_WheelA_Cylinder_001_mesh_vtx_0[36];
extern Gfx totwc_dl_WheelA_Cylinder_001_mesh_tri_0[];
extern Vtx totwc_dl_WheelA_Cylinder_001_mesh_vtx_1[42];
extern Gfx totwc_dl_WheelA_Cylinder_001_mesh_tri_1[];
extern Vtx totwc_dl_WheelB_Cylinder_001_mesh_vtx_0[36];
extern Gfx totwc_dl_WheelB_Cylinder_001_mesh_tri_0[];
extern Vtx totwc_dl_WheelB_Cylinder_001_mesh_vtx_1[42];
extern Gfx totwc_dl_WheelB_Cylinder_001_mesh_tri_1[];
extern Vtx totwc_dl_Wheel__F__Cylinder_001_mesh_vtx_0[36];
extern Gfx totwc_dl_Wheel__F__Cylinder_001_mesh_tri_0[];
extern Vtx totwc_dl_Wheel__F__Cylinder_001_mesh_vtx_1[42];
extern Gfx totwc_dl_Wheel__F__Cylinder_001_mesh_tri_1[];
extern Vtx totwc_dl_WingA_Cube_001_mesh_vtx_0[102];
extern Gfx totwc_dl_WingA_Cube_001_mesh_tri_0[];
extern Vtx totwc_dl_WingA_Cube_001_mesh_vtx_1[4];
extern Gfx totwc_dl_WingA_Cube_001_mesh_tri_1[];
extern Vtx totwc_dl_WingB_Cube_001_mesh_vtx_0[102];
extern Gfx totwc_dl_WingB_Cube_001_mesh_tri_0[];
extern Vtx totwc_dl_WingB_Cube_001_mesh_vtx_1[4];
extern Gfx totwc_dl_WingB_Cube_001_mesh_tri_1[];

extern Gfx totwc_dl_Airplane_001_mesh[];
extern Gfx totwc_dl_EngineA_Cylinder_002_mesh[];
extern Gfx totwc_dl_EngineB_Cylinder_001_mesh[];
extern Gfx totwc_dl_Engine_Support_Cube_001_mesh[];
extern Gfx totwc_dl_TailFin_Cube_001_mesh[];
extern Gfx totwc_dl_WheelA_Cylinder_001_mesh[];
extern Gfx totwc_dl_WheelB_Cylinder_001_mesh[];
extern Gfx totwc_dl_Wheel__F__Cylinder_001_mesh[];
extern Gfx totwc_dl_WingA_Cube_001_mesh[];
extern Gfx totwc_dl_WingB_Cube_001_mesh[];
extern Gfx totwc_dl_material_revert_render_settings[];

