extern const GeoLayout wmotr_area_1_geo[];
extern const GeoLayout wmotr_area_1[];
extern const Collision wmotr_area_1_collision[];
extern const MacroObject wmotr_area_1_Area_root_macro_objs[];
extern Vtx wmotr_dl_Airplane_001_mesh_vtx_0[578];
extern Gfx wmotr_dl_Airplane_001_mesh_tri_0[];
extern Vtx wmotr_dl_Airplane_001_mesh_vtx_1[63];
extern Gfx wmotr_dl_Airplane_001_mesh_tri_1[];
extern Vtx wmotr_dl_Airplane_001_mesh_vtx_2[18];
extern Gfx wmotr_dl_Airplane_001_mesh_tri_2[];
extern Vtx wmotr_dl_EngineA_Cylinder_002_mesh_vtx_0[55];
extern Gfx wmotr_dl_EngineA_Cylinder_002_mesh_tri_0[];
extern Vtx wmotr_dl_EngineB_Cylinder_001_mesh_vtx_0[55];
extern Gfx wmotr_dl_EngineB_Cylinder_001_mesh_tri_0[];
extern Vtx wmotr_dl_Engine_Support_Cube_001_mesh_vtx_0[14];
extern Gfx wmotr_dl_Engine_Support_Cube_001_mesh_tri_0[];
extern Vtx wmotr_dl_TailFin_Cube_001_mesh_vtx_0[53];
extern Gfx wmotr_dl_TailFin_Cube_001_mesh_tri_0[];
extern Vtx wmotr_dl_WingA_Cube_001_mesh_vtx_0[62];
extern Gfx wmotr_dl_WingA_Cube_001_mesh_tri_0[];
extern Vtx wmotr_dl_WingA_Cube_001_mesh_vtx_1[4];
extern Gfx wmotr_dl_WingA_Cube_001_mesh_tri_1[];
extern Vtx wmotr_dl_WingB_Cube_001_mesh_vtx_0[62];
extern Gfx wmotr_dl_WingB_Cube_001_mesh_tri_0[];
extern Vtx wmotr_dl_WingB_Cube_001_mesh_vtx_1[4];
extern Gfx wmotr_dl_WingB_Cube_001_mesh_tri_1[];
extern Vtx wmotr_dl_Sea_mesh_vtx_0[4];
extern Gfx wmotr_dl_Sea_mesh_tri_0[];

extern Gfx wmotr_dl_Airplane_001_mesh[];
extern Gfx wmotr_dl_EngineA_Cylinder_002_mesh[];
extern Gfx wmotr_dl_EngineB_Cylinder_001_mesh[];
extern Gfx wmotr_dl_Engine_Support_Cube_001_mesh[];
extern Gfx wmotr_dl_TailFin_Cube_001_mesh[];
extern Gfx wmotr_dl_WingA_Cube_001_mesh[];
extern Gfx wmotr_dl_WingB_Cube_001_mesh[];
extern Gfx wmotr_dl_Sea_mesh[];
extern Gfx wmotr_dl_material_revert_render_settings[];

