extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_Area_root_macro_objs[];
extern Vtx bob_dl_Map_mesh_vtx_0[78];
extern Gfx bob_dl_Map_mesh_tri_0[];
extern Vtx bob_dl_Map_mesh_vtx_1[52];
extern Gfx bob_dl_Map_mesh_tri_1[];
extern Vtx bob_dl_Map_mesh_vtx_2[150];
extern Gfx bob_dl_Map_mesh_tri_2[];
extern Vtx bob_dl_Map_mesh_vtx_3[20];
extern Gfx bob_dl_Map_mesh_tri_3[];
extern Vtx bob_dl_Map_mesh_vtx_4[20];
extern Gfx bob_dl_Map_mesh_tri_4[];
extern Vtx bob_dl_Map_mesh_vtx_5[4];
extern Gfx bob_dl_Map_mesh_tri_5[];
extern Vtx bob_dl_Airplane_mesh_vtx_0[164];
extern Gfx bob_dl_Airplane_mesh_tri_0[];
extern Vtx bob_dl_Airplane_nonsolid_mesh_vtx_0[132];
extern Gfx bob_dl_Airplane_nonsolid_mesh_tri_0[];
extern Vtx bob_dl_BackgroundRoad_mesh_vtx_0[12];
extern Gfx bob_dl_BackgroundRoad_mesh_tri_0[];
extern Vtx bob_dl_BackgroundRoad_mesh_vtx_1[16];
extern Gfx bob_dl_BackgroundRoad_mesh_tri_1[];
extern Vtx bob_dl_BackgroundRoad_mesh_vtx_2[6];
extern Gfx bob_dl_BackgroundRoad_mesh_tri_2[];
extern Vtx bob_dl_Buildings_mesh_vtx_0[336];
extern Gfx bob_dl_Buildings_mesh_tri_0[];

extern Gfx bob_dl_Map_mesh[];
extern Gfx bob_dl_Airplane_mesh[];
extern Gfx bob_dl_Airplane_nonsolid_mesh[];
extern Gfx bob_dl_BackgroundRoad_mesh[];
extern Gfx bob_dl_Buildings_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];

