#include "src/game/envfx_snow.h"

const GeoLayout bob_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_Map_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 858, -1190, -2819, bob_dl_Airplane_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_EngineA_Cylinder_001_mesh),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_EngineB_Cylinder_006_mesh),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_Engine_Support_Cube_010_mesh),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_TailFin_Cube_011_mesh),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_WheelA_Cylinder_005_mesh),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_WheelB_Cylinder_004_mesh),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_Wheel__F__Cylinder_003_mesh),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_WingA_Cube_mesh),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_WingB_Cube_002_mesh),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_BackgroundRoad_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -5696, -1540, -340, bob_dl_Buildings_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_GREEN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 9, 1548, 2862, 9, 1335, 2862, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
