extern const GeoLayout airplane_geo[];
extern Vtx airplane_Airplane_001_mesh_vtx_0[578];
extern Gfx airplane_Airplane_001_mesh_tri_0[];
extern Vtx airplane_Airplane_001_mesh_vtx_1[63];
extern Gfx airplane_Airplane_001_mesh_tri_1[];
extern Vtx airplane_Airplane_001_mesh_vtx_2[18];
extern Gfx airplane_Airplane_001_mesh_tri_2[];
extern Vtx airplane_EngineA_Cylinder_002_mesh_vtx_0[55];
extern Gfx airplane_EngineA_Cylinder_002_mesh_tri_0[];
extern Vtx airplane_EngineB_Cylinder_001_mesh_vtx_0[55];
extern Gfx airplane_EngineB_Cylinder_001_mesh_tri_0[];
extern Vtx airplane_Engine_Support_Cube_001_mesh_vtx_0[14];
extern Gfx airplane_Engine_Support_Cube_001_mesh_tri_0[];
extern Vtx airplane_TailFin_Cube_001_mesh_vtx_0[53];
extern Gfx airplane_TailFin_Cube_001_mesh_tri_0[];
extern Vtx airplane_WingA_Cube_001_mesh_vtx_0[62];
extern Gfx airplane_WingA_Cube_001_mesh_tri_0[];
extern Vtx airplane_WingA_Cube_001_mesh_vtx_1[4];
extern Gfx airplane_WingA_Cube_001_mesh_tri_1[];
extern Vtx airplane_WingB_Cube_001_mesh_vtx_0[62];
extern Gfx airplane_WingB_Cube_001_mesh_tri_0[];
extern Vtx airplane_WingB_Cube_001_mesh_vtx_1[4];
extern Gfx airplane_WingB_Cube_001_mesh_tri_1[];

extern Gfx airplane_Airplane_001_mesh[];
extern Gfx airplane_EngineA_Cylinder_002_mesh[];
extern Gfx airplane_EngineB_Cylinder_001_mesh[];
extern Gfx airplane_Engine_Support_Cube_001_mesh[];
extern Gfx airplane_TailFin_Cube_001_mesh[];
extern Gfx airplane_WingA_Cube_001_mesh[];
extern Gfx airplane_WingB_Cube_001_mesh[];
extern Gfx airplane_material_revert_render_settings[];

